apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: null
  generation: 1
  labels:
    app: mongo
    app.kubernetes.io/component: mongo
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/part-of: netrunner-git-app
  name: mongo
  selfLink: /apis/apps.openshift.io/v1/namespaces/brandon-test/deploymentconfigs/mongo
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: mongo
    deploymentconfig: mongo
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: mongo
        deploymentconfig: mongo
    spec:
      containers:
      - image: mongo@sha256:78d4ab54b101245d2cfa60a82e6cca68fb03d42795e71b1019ddd6b92f680b9c
        imagePullPolicy: IfNotPresent
        name: mongo
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/configdb
          name: mongo-1
        - mountPath: /data/db
          name: mongo-2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: mongo-1
      - emptyDir: {}
        name: mongo-2
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - mongo
      from:
        kind: ImageStreamTag
        name: mongo:3.6.8
        namespace: brandon-test
    type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
