apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: "2020-01-15T20:48:18Z"
  creationTimestamp: null
  generation: 1
  labels:
    app: mongo
    app.kubernetes.io/component: mongo
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/part-of: netrunner-git-app
  name: mongo
  selfLink: /apis/image.openshift.io/v1/namespaces/brandon-test/imagestreams/mongo
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/imported-from: mongo:3.6.8
    from:
      kind: DockerImage
      name: mongo:3.6.8
    generation: 1
    importPolicy: {}
    name: 3.6.8
    referencePolicy:
      type: Source
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/mongo
