apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: jnet
  name: jnet
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: jnet
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
