apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
    volume.kubernetes.io/selected-node: ip-10-0-133-235.ca-central-1.compute.internal
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  name: netrunner-data
  selfLink: /api/v1/namespaces/brandon-test/persistentvolumeclaims/netrunner-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: pvc-8d428199-37c0-11ea-89ec-02637b2b3cea
status: {}
