apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/connects-to: mongodb,mongo
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/brandonwilliamsised/netrunner.git
  creationTimestamp: null
  labels:
    app: netrunner-git
    app.kubernetes.io/component: netrunner-git
    app.kubernetes.io/instance: netrunner-git
    app.kubernetes.io/part-of: netrunner-git-app
  name: netrunner-git
  selfLink: /api/v1/namespaces/brandon-test/services/netrunner-git
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 1042
  selector:
    app: netrunner-git
    deploymentconfig: netrunner-git
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
